const {
  COMPONENT_PATH_PREFIX,
  BUSINESS_COMPONENT_PATH_PREFIX,
  COMMON_TEMPLATE_PATH_PREFIX,
} = require('../config/constant');

module.exports = {

  templates: [{
    name: "tpl-sass",
    path: `tpl-sass`,
    desc: 'sass开发的小程序模板',
  }, {
    name: "tpl-subpackage-sass",
    path: `tpl-subpackage-sass`,
    desc: 'sass开发的提供分包小程序模板',
  }],

  components: [{
    name: "canvas-to-image",
    path: `${COMPONENT_PATH_PREFIX}/canvas-to-image`,
    class: '功能组件',
    desc: '画布转图片',
  }, {
    name: "photo-identification",
    path: `${COMPONENT_PATH_PREFIX}/photo-identification`,
    class: '功能组件',
    desc: '拍照或选择相册OCR识别',
  }, {
    name: "chat",
    path: `${COMPONENT_PATH_PREFIX}/chat`,
    class: '功能组件',
    desc: '聊天页',
  }, {
    name: "label-input",
    path: `${COMPONENT_PATH_PREFIX}/label-input`,
    class: 'UI型表单处理组件',
    desc: '输入框',
  }, {
    name: "label-picker",
    path: `${COMPONENT_PATH_PREFIX}/label-picker`,
    class: 'UI型表单处理组件',
    desc: '选择器',
  }, {
    name: "label-textarea",
    path: `${COMPONENT_PATH_PREFIX}/label-textarea`,
    class: 'UI型表单处理组件',
    desc: '文本区域',
  }, {
    name: "select-box",
    path: `${COMPONENT_PATH_PREFIX}/select-box`,
    class: 'UI型表单处理组件',
    desc: '复选框',
  }, {
    name: "kg-*[text|input|switch|picker|search-input|expandable-text|expandable-picker]",
    path: COMMON_TEMPLATE_PATH_PREFIX,
    class: '表单模板',
    desc: '包括文本框、输入框、开关、选择器、搜索提示输入框、可展开的文本框、可展开的选择器',
  }, {
    name: "image-collect",
    path: `${COMPONENT_PATH_PREFIX}/image-collect`,
    class: 'UI型图片处理组件',
    desc: '图片上传（上传逻辑自行外部实现）',
  }, {
    name: "image-cropper",
    path: `${COMPONENT_PATH_PREFIX}/image-cropper`,
    class: 'UI型图片处理组件',
    desc: '图片裁剪器',
  }, {
    name: "image-list",
    path: `${COMPONENT_PATH_PREFIX}/image-list`,
    class: 'UI型图片处理组件',
    desc: '图片列表',
  }, {
    name: "image-swiper",
    path: `${COMPONENT_PATH_PREFIX}/image-swiper`,
    class: 'UI型图片处理组件',
    desc: '图片轮播',
  }, {
    name: "upload-image",
    path: `${COMPONENT_PATH_PREFIX}/upload-image`,
    class: 'UI型图片处理组件',
    desc: '图片上传（支持单图片即时上传）',
  }, {
    name: "preview-image",
    path: `${COMPONENT_PATH_PREFIX}/preview-image`,
    class: 'UI型图片处理组件',
    desc: '图片预览',
  }, {
    name: "abbreviation-text",
    path: `${COMPONENT_PATH_PREFIX}/abbreviation-text`,
    class: 'UI型文本处理组件',
    desc: '支持展开折叠的多行文本',
  }, {
    name: "text-identification",
    path: `${COMPONENT_PATH_PREFIX}/text-identification`,
    class: 'UI型文本处理组件',
    desc: '文本识别',
  }, {
    name: "base-modal",
    path: `${COMPONENT_PATH_PREFIX}/base-modal`,
    class: 'UI型对话框组件',
    desc: '基本模态框',
  }, {
    name: "list-item",
    path: `${COMPONENT_PATH_PREFIX}/list-item`,
    class: 'UI型列表、条目组件',
    desc: '列表条目',
  }, {
    name: "message-item",
    path: `${COMPONENT_PATH_PREFIX}/message-item`,
    class: 'UI型列表、条目组件',
    desc: '消息条目',
  }, {
    name: "recommend-list",
    path: `${COMPONENT_PATH_PREFIX}/recommend-list`,
    class: 'UI型列表、条目组件',
    desc: '推荐列表',
  }, {
    name: "pull-down-list",
    path: `${COMPONENT_PATH_PREFIX}/pull-down-list`,
    class: 'UI型列表、条目组件',
    desc: '下拉列表',
  }, {
    name: "two-column-list",
    path: `${COMPONENT_PATH_PREFIX}/two-column-list`,
    class: 'UI型列表、条目组件',
    desc: '双列列表',
  }, {
    name: "table",
    path: `${COMPONENT_PATH_PREFIX}/table`,
    class: 'UI型表格组件',
    desc: '表格',
  }, {
    name: "card",
    path: `${COMPONENT_PATH_PREFIX}/card`,
    class: 'UI型名片组件',
    desc: '微信名片',
  }, {
    name: "personal-card",
    path: `${COMPONENT_PATH_PREFIX}/personal-card`,
    class: 'UI型名片组件',
    desc: '个人名片',
  }, {
    name: "standard-box",
    path: `${COMPONENT_PATH_PREFIX}/standard-box`,
    class: 'UI型盒组件',
    desc: '标准盒',
  }, {
    name: "panel",
    path: `${COMPONENT_PATH_PREFIX}/panel`,
    class: 'UI型盒组件',
    desc: '面板',
  }, {
    name: "orange-box",
    path: `${COMPONENT_PATH_PREFIX}/orange-box`,
    class: 'UI型盒组件',
    desc: '橘色盒',
  }, {
    name: "button-group",
    path: `${COMPONENT_PATH_PREFIX}/button-group`,
    class: 'UI型其他通用组件',
    desc: '按钮组',
  }, {
    name: "tip-header",
    path: `${COMPONENT_PATH_PREFIX}/tip-header`,
    class: 'UI型其他通用组件',
    desc: '带提示的区域头部',
  }, {
    name: "nav-pager",
    path: `${COMPONENT_PATH_PREFIX}/nav-pager`,
    class: 'UI型其他通用组件',
    desc: '导航分页器',
  }, {
    name: "link-view",
    path: `${COMPONENT_PATH_PREFIX}/link-view`,
    class: 'UI型其他通用组件',
    desc: '链接',
  }, {
    name: "nav-bar",
    path: `${COMPONENT_PATH_PREFIX}/nav-bar`,
    class: 'UI型其他通用组件',
    desc: '导航栏',
  }, {
    name: "no-content",
    path: `${COMPONENT_PATH_PREFIX}/no-content`,
    class: 'UI型其他通用组件',
    desc: '空内容提示',
  }, {
    name: "num-header",
    path: `${COMPONENT_PATH_PREFIX}/num-header`,
    class: 'UI型其他通用组件',
    desc: '带数字序号的区域头部',
  }, {
    name: "video-view",
    path: `${COMPONENT_PATH_PREFIX}/video-view`,
    class: 'UI型其他通用组件',
    desc: '视频组件',
  }, {
    name: "authorize-modal",
    path: `${BUSINESS_COMPONENT_PATH_PREFIX}/authorize-modal`,
    class: '业务组件',
    desc: '授权对话框',
  }, {
    name: "get-discount",
    path: `${BUSINESS_COMPONENT_PATH_PREFIX}/get-discount`,
    class: '业务组件',
    desc: '优惠',
  }, {
    name: "get-discount-modal",
    path: `${BUSINESS_COMPONENT_PATH_PREFIX}/get-discount-modal`,
    class: '业务组件',
    desc: '优惠对话框',
  }, {
    name: "subscribe-modal",
    path: `${BUSINESS_COMPONENT_PATH_PREFIX}/subscribe-modal`,
    class: '业务组件',
    desc: '模板订阅框',
  }]
}
